services:
  octopus:
    image: raynmy/octopus:v1.0.2
    build:
      context: .
      dockerfile: scripts/dockerfiles/Dockerfile.alpine
      args:
        TARGETPLATFORM: linux/amd64
    ports:
       - '8080:8080'
    volumes:
       - './data:/app/data'
    container_name: octopus-new
    restart: unless-stopped
